//  DELETE FROM dba.fr_canales_hist  ;
//  DELETE FROM dba.fr_canales  ;
//  DELETE FROM dba.fr_ganados_hist  ;
//  DELETE FROM dba.fr_ganados  ;
//DELETE FROM dba.fr_recaudo  ;
//DELETE FROM dba.fr_sac_propios  ;
//DELETE FROM dba.fr_items_entrada  ;
//DELETE FROM dba.fr_enc_entrada  ;
//DELETE FROM dba.fr_items_factura  ;
//DELETE FROM dba.fr_encab_factura  ;
//DELETE FROM dba.fr_encab_plan_sacrif  ;
//DELETE FROM dba.fr_encab_retiros  ;
//DELETE FROM dba.fr_items_pago_plan_sacrif  ;
//DELETE FROM dba.fr_items_plan_sacrif  ;
//DELETE FROM dba.fr_items_rechazos  ;
//DELETE FROM dba.fr_enc_rechazos  ;
//DELETE FROM dba.fr_paletas_x_subasta  ;
//DELETE FROM dba.fr_encab_subasta  ;
//DELETE FROM dba.fr_prog_sacrif_mayor  ;