  SELECT dba.fr_ganados.id_empresa,   
         dba.fr_ganados.id_documento,   
         dba.fr_ganados.id_entrada,   
         dba.fr_ganados.id_res,   
         dba.fr_ganados.ind_esp_mayor,   
         dba.fr_ganados.id_linea,   
         dba.fr_ganados.fec_bscla_indvdual,   
         dba.fr_ganados.sexo,   
         dba.fr_ganados.peso,   
         dba.fr_ganados.estado_animal,   
         dba.fr_ganados.id_usuario,   
         dba.fr_ganados.fec_registro,   
         dba.fr_ganados.val_unitario_bascula,   
         dba.fr_ganados.val_unitario_corrales,   
         dba.fr_ganados.val_unitario_sacrificio,   
         dba.fr_ganados.id_doc_factura_sac,   
         dba.fr_ganados.id_factura_sac,   
         dba.fr_ganados.nit_fact_sacrif,   
         dba.fr_ganados.nombre_fact_sacrif,   
         dba.fr_ganados.fecha_factura_sacrificio,   
         dba.fr_ganados.ind_propio,   
         dba.fr_ganados.id_doc_sacr,   
         dba.fr_ganados.id_sacr,   
         dba.fr_ganados.val_unitario_flete,   
         dba.fr_ganados.plaza_carne1,   
         dba.fr_ganados.pto_carne1,   
         dba.fr_ganados.ind_codificacion_mercagan  
    FROM dba.fr_ganados  
   WHERE dba.fr_ganados.id_entrada = 15502  ;
