  SELECT dba.fr_recaudo.id_empresa,   
         dba.fr_recaudo.id_recaudo,   
         dba.fr_recaudo.num_recaudo,   
         dba.fr_recaudo.id_evento_fac,   
         dba.fr_recaudo.id_factura,   
         dba.fr_recaudo.num_factura,   
         dba.fr_recaudo.impreso_factura,   
         dba.fr_recaudo.total_factura,   
         dba.fr_recaudo.total_fac_sin_iva,   
         dba.fr_recaudo.total_iva_fac,   
         dba.fr_recaudo.nit_factura,   
         dba.fr_recaudo.nombre_factura,   
         dba.fr_recaudo.id_medio_pago,   
         dba.fr_recaudo.dinero_entregado,   
         dba.fr_recaudo.id_banco,   
         dba.fr_recaudo.num_cuenta,   
         dba.fr_recaudo.num_cheque,   
         dba.fr_recaudo.telefonos,   
         dba.fr_recaudo.id_usuario,   
         dba.fr_recaudo.fec_registro,   
         dba.fr_recaudo.fec_recaudo,   
         dba.fr_recaudo.fec_cheque,   
         dba.fr_recaudo.usr_anula,   
         dba.fr_recaudo.fec_anula,   
         dba.fr_recaudo.estado,   
         dba.fr_recaudo.num_bono,   
         dba.fr_recaudo.efectivo_mixto,   
         dba.fr_recaudo.cheque_mixto,   
         dba.fr_recaudo.bono_mixto,   
         dba.fr_recaudo.credito_mixto,   
         dba.fr_recaudo.dias_credito,   
         dba.fr_recaudo.id_forma_pago  
    FROM dba.fr_recaudo  
   WHERE dba.fr_recaudo.num_recaudo in(81925)  ;
