//  UPDATE dba.fr_items_factura  
//     SET id_doc_factura = 'XX'  
//   WHERE (dba.fr_items_factura.id_factura >= 1 AND  
//         dba.fr_items_factura.id_factura <= 30000)   ;
//
//
//  UPDATE dba.fr_encab_factura  
//     SET id_doc_factura = 'XX'  
//   WHERE (dba.fr_encab_factura.id_factura >= 1 AND  
//         dba.fr_encab_factura.id_factura <= 30000)   ;

//  UPDATE dba.fr_ganados  
//     SET id_doc_factura_sac = 'XX'  
//   WHERE dba.fr_ganados.id_doc_factura_sac = 'FB'   ;

//  UPDATE dba.fr_ganados_hist  
//     SET id_doc_factura_sac = 'XX'  
//   WHERE dba.fr_ganados_hist.id_doc_factura_sac = 'FB'   ;

//  UPDATE dba.fr_recaudo  
//     SET id_factura = 'XX'  
//   WHERE dba.fr_recaudo.id_factura = 'FB'   ;



//  SELECT dba.fr_encab_factura.id_empresa,   
//         dba.fr_encab_factura.id_doc_factura,   
//         dba.fr_encab_factura.id_factura,   
//         dba.fr_encab_factura.id_doc,   
//         dba.fr_encab_factura.id_entrada,   
//         dba.fr_encab_factura.id_fact_prmprso,   
//         dba.fr_encab_factura.cod_alterno,   
//         dba.fr_encab_factura.fec_factura,   
//         dba.fr_encab_factura.ind_lin_mayor,   
//         dba.fr_encab_factura.id_especie,   
//         dba.fr_encab_factura.id_propietario,   
//         dba.fr_encab_factura.nombre_propietario,   
//         dba.fr_encab_factura.total_factura,   
//         dba.fr_encab_factura.id_usuario,   
//         dba.fr_encab_factura.fec_registro,   
//         dba.fr_encab_factura.ind_pagado,   
//         dba.fr_encab_factura.id_comprador,   
//         dba.fr_encab_factura.nombre_comprador,   
//         dba.fr_encab_factura.nit_factura,   
//         dba.fr_encab_factura.nombre_factura,   
//         dba.fr_encab_factura.tipo_entrada,   
//         dba.fr_encab_factura.cant_animales,   
//         dba.fr_encab_factura.total_kilos,   
//         dba.fr_encab_factura.fecha_ingreso,   
//         dba.fr_encab_factura.total_fact_sin_iva,   
//         dba.fr_encab_factura.total_iva_fact,   
//         dba.fr_encab_factura.total_factura_letras,   
//         dba.fr_encab_factura.id_evento_fac,   
//         dba.fr_encab_factura.n_paleta,   
//         dba.fr_encab_factura.n_subasta,   
//         dba.fr_encab_factura.prec_base_kilo,   
//         dba.fr_encab_factura.prec_final_base_kilo,   
//         dba.fr_encab_factura.id_comprobante,   
//         dba.fr_encab_factura.cod_comprobante,   
//         dba.fr_encab_factura.estado_contable,   
//         dba.fr_encab_factura.ind_flete,   
//         dba.fr_encab_factura.ruta_flete,   
//         dba.fr_encab_factura.sitio_factura  
//    FROM dba.fr_encab_factura  
//   WHERE dba.fr_encab_factura.id_doc_factura <> 'XX'   ;

//  SELECT dba.fr_canales.id_empresa,   
//         dba.fr_canales.id_documento,   
//         dba.fr_canales.id_entrada,   
//         dba.fr_canales.id_res,   
//         dba.fr_canales.peso_canal_uno,   
//         dba.fr_canales.peso_canal_dos,   
//         dba.fr_canales.peso_total_canal,   
//         dba.fr_canales.peso_visceras,   
//         dba.fr_canales.estado,   
//         dba.fr_canales.id_usuario,   
//         dba.fr_canales.fec_registro,   
//         dba.fr_canales.peso_total_salida_canal,   
//         dba.fr_canales.peso_salida_visceras,   
//         dba.fr_canales.peso_pierna_1,   
//         dba.fr_canales.peso_pierna_2,   
//         dba.fr_canales.peso_costillar,   
//         dba.fr_canales.fec_ingreso  
//    FROM dba.fr_canales  
//   WHERE dba.fr_canales.id_res = '05749'   ;
  SELECT dba.fr_ganados.id_empresa,   
         dba.fr_ganados.id_documento,   
         dba.fr_ganados.id_entrada,   
         dba.fr_ganados.id_res,   
         dba.fr_ganados.ind_esp_mayor,   
         dba.fr_ganados.id_linea,   
         dba.fr_ganados.id_tipo_corral_r,   
         dba.fr_ganados.id_corral_r,   
         dba.fr_ganados.id_tipo_corral_c,   
         dba.fr_ganados.id_corral_c,   
         dba.fr_ganados.fec_bscla_indvdual,   
         dba.fr_ganados.sexo,   
         dba.fr_ganados.id_bascula,   
         dba.fr_ganados.id_raza,   
         dba.fr_ganados.peso,   
         dba.fr_ganados.descrip_animal,   
         dba.fr_ganados.estado_animal,   
         dba.fr_ganados.id_usuario,   
         dba.fr_ganados.fec_registro,   
         dba.fr_ganados.id_propietario,   
         dba.fr_ganados.nombre_propietario,   
         dba.fr_ganados.id_pesador,   
         dba.fr_ganados.edad,   
         dba.fr_ganados.val_unitario_bascula,   
         dba.fr_ganados.val_unitario_corrales,   
         dba.fr_ganados.val_unitario_sacrificio,   
         dba.fr_ganados.ind_pesaje_especial,   
         dba.fr_ganados.plaza_carne,   
         dba.fr_ganados.pto_carne,   
         dba.fr_ganados.plaza_visc,   
         dba.fr_ganados.pto_visc,   
         dba.fr_ganados.id_tipo_corral_s,   
         dba.fr_ganados.id_corral_s,   
         dba.fr_ganados.id_doc_factura_sac,   
         dba.fr_ganados.id_factura_sac,   
         dba.fr_ganados.id_doc_retiros,   
         dba.fr_ganados.id_retiro,   
         dba.fr_ganados.ind_peso_manual,   
         dba.fr_ganados.peso_canal_uno,   
         dba.fr_ganados.peso_canal_dos,   
         dba.fr_ganados.peso_total_canal,   
         dba.fr_ganados.peso_visceras,   
         dba.fr_ganados.peso_salida_total_canal,   
         dba.fr_ganados.peso_salida_visceras,   
         dba.fr_ganados.comprador_piel,   
         dba.fr_ganados.peso_pierna1,   
         dba.fr_ganados.peso_pierna2,   
         dba.fr_ganados.peso_costillar,   
         dba.fr_ganados.nit_fact_sacrif,   
         dba.fr_ganados.nombre_fact_sacrif,   
         dba.fr_ganados.n_intercambios,   
         dba.fr_ganados.tipo_entrada,   
         dba.fr_ganados.procedencia,   
         dba.fr_ganados.fecha_factura_sacrificio,   
         dba.fr_ganados.ind_propio,   
         dba.fr_ganados.id_doc_sacr,   
         dba.fr_ganados.id_sacr,   
         dba.fr_ganados.val_unitario_flete  
    FROM dba.fr_ganados  
   WHERE dba.fr_ganados.id_res = '24433'   ;
//
//  SELECT dba.fr_encab_factura.id_empresa,   
//         dba.fr_encab_factura.id_doc_factura,   
//         dba.fr_encab_factura.id_factura,   
//         dba.fr_encab_factura.id_doc,   
//         dba.fr_encab_factura.id_entrada,   
//         dba.fr_encab_factura.id_fact_prmprso,   
//         dba.fr_encab_factura.cod_alterno,   
//         dba.fr_encab_factura.fec_factura,   
//         dba.fr_encab_factura.ind_lin_mayor,   
//         dba.fr_encab_factura.id_especie,   
//         dba.fr_encab_factura.id_propietario,   
//         dba.fr_encab_factura.nombre_propietario,   
//         dba.fr_encab_factura.total_factura,   
//         dba.fr_encab_factura.id_usuario,   
//         dba.fr_encab_factura.fec_registro,   
//         dba.fr_encab_factura.ind_pagado,   
//         dba.fr_encab_factura.id_comprador,   
//         dba.fr_encab_factura.nombre_comprador,   
//         dba.fr_encab_factura.nit_factura,   
//         dba.fr_encab_factura.nombre_factura,   
//         dba.fr_encab_factura.tipo_entrada,   
//         dba.fr_encab_factura.cant_animales,   
//         dba.fr_encab_factura.total_kilos,   
//         dba.fr_encab_factura.fecha_ingreso,   
//         dba.fr_encab_factura.total_fact_sin_iva,   
//         dba.fr_encab_factura.total_iva_fact,   
//         dba.fr_encab_factura.total_factura_letras,   
//         dba.fr_encab_factura.id_evento_fac,   
//         dba.fr_encab_factura.n_paleta,   
//         dba.fr_encab_factura.n_subasta,   
//         dba.fr_encab_factura.prec_base_kilo,   
//         dba.fr_encab_factura.prec_final_base_kilo,   
//         dba.fr_encab_factura.id_comprobante,   
//         dba.fr_encab_factura.cod_comprobante,   
//         dba.fr_encab_factura.estado_contable,   
//         dba.fr_encab_factura.ind_flete,   
//         dba.fr_encab_factura.ruta_flete,   
//         dba.fr_encab_factura.sitio_factura  
//    FROM dba.fr_encab_factura  
//   WHERE ( dba.fr_encab_factura.id_doc_factura = 'FB' ) AND  
//         ( dba.fr_encab_factura.id_factura = 3066 )   ;
//  SELECT dba.fr_recaudo.id_empresa,   
//         dba.fr_recaudo.id_recaudo,   
//         dba.fr_recaudo.num_recaudo,   
//         dba.fr_recaudo.id_evento_fac,   
//         dba.fr_recaudo.id_factura,   
//         dba.fr_recaudo.num_factura,   
//         dba.fr_recaudo.impreso_factura,   
//         dba.fr_recaudo.total_factura,   
//         dba.fr_recaudo.total_fac_sin_iva,   
//         dba.fr_recaudo.total_iva_fac,   
//         dba.fr_recaudo.nit_factura,   
//         dba.fr_recaudo.nombre_factura,   
//         dba.fr_recaudo.id_medio_pago,   
//         dba.fr_recaudo.dinero_entregado,   
//         dba.fr_recaudo.id_banco,   
//         dba.fr_recaudo.num_cuenta,   
//         dba.fr_recaudo.num_cheque,   
//         dba.fr_recaudo.telefonos,   
//         dba.fr_recaudo.id_usuario,   
//         dba.fr_recaudo.fec_registro,   
//         dba.fr_recaudo.fec_recaudo,   
//         dba.fr_recaudo.fec_cheque,   
//         dba.fr_recaudo.usr_anula,   
//         dba.fr_recaudo.fec_anula,   
//         dba.fr_recaudo.estado,   
//         dba.fr_recaudo.num_bono,   
//         dba.fr_recaudo.efectivo_mixto,   
//         dba.fr_recaudo.cheque_mixto,   
//         dba.fr_recaudo.bono_mixto,   
//         dba.fr_recaudo.credito_mixto,   
//         dba.fr_recaudo.dias_credito  
//    FROM dba.fr_recaudo  
//   WHERE dba.fr_recaudo.num_recaudo = 27516   ;


//  SELECT dba.fr_enc_entrada.id_empresa,   
//         dba.fr_enc_entrada.id_documento,   
//         dba.fr_enc_entrada.id_entrada,   
//         dba.fr_enc_entrada.fecha_ingreso,   
//         dba.fr_enc_entrada.tipo_entrada,   
//         dba.fr_enc_entrada.ind_esp_mayor,   
//         dba.fr_enc_entrada.id_linea,   
//         dba.fr_enc_entrada.ind_propio,   
//         dba.fr_enc_entrada.id_propietario,   
//         dba.fr_enc_entrada.nombre_propietario,   
//         dba.fr_enc_entrada.procedencia,   
//         dba.fr_enc_entrada.vehiculo,   
//         dba.fr_enc_entrada.id_conductor,   
//         dba.fr_enc_entrada.nombre_conductor,   
//         dba.fr_enc_entrada.id_tipo_corral_r,   
//         dba.fr_enc_entrada.id_corral_r,   
//         dba.fr_enc_entrada.estado_entrada,   
//         dba.fr_enc_entrada.observaciones,   
//         dba.fr_enc_entrada.id_usuario,   
//         dba.fr_enc_entrada.fec_registro,   
//         dba.fr_enc_entrada.peso_global_lote,   
//         dba.fr_enc_entrada.ind_bascula,   
//         dba.fr_enc_entrada.fec_bascula,   
//         dba.fr_enc_entrada.usuario_bascula,   
//         dba.fr_enc_entrada.numero_guia,   
//         dba.fr_enc_entrada.nmro_reg_sanitario,   
//         dba.fr_enc_entrada.usr_ingreso,   
//         dba.fr_enc_entrada.nmro_bono_venta,   
//         dba.fr_enc_entrada.cant_animales,   
//         dba.fr_enc_entrada.id_tipo_corral_c,   
//         dba.fr_enc_entrada.id_corral_c,   
//         dba.fr_enc_entrada.usr_corral_c,   
//         dba.fr_enc_entrada.fec_corral_c,   
//         dba.fr_enc_entrada.secuencia_pesaje,   
//         dba.fr_enc_entrada.secuencia_subasta,   
//         dba.fr_enc_entrada.usr_secuencia_subasta,   
//         dba.fr_enc_entrada.fec_sec_subasta,   
//         dba.fr_enc_entrada.prec_base_kilo,   
//         dba.fr_enc_entrada.prec_final_base_kilo,   
//         dba.fr_enc_entrada.id_doc_fact_vtas_subasta,   
//         dba.fr_enc_entrada.id_fact_vtas_subasta,   
//         dba.fr_enc_entrada.consec_subasta  
//    FROM dba.fr_enc_entrada  
//   WHERE dba.fr_enc_entrada.id_entrada = 10347   ;

//  SELECT dba.fr_items_factura.id_empresa,   
//         dba.fr_items_factura.id_doc_factura,   
//         dba.fr_items_factura.id_factura,   
//         dba.fr_items_factura.id_concepto,   
//         dba.fr_items_factura.ind_lin_mayor,   
//         dba.fr_items_factura.id_especie,   
//         dba.fr_items_factura.unidad_concepto,   
//         dba.fr_items_factura.cantidad_concepto,   
//         dba.fr_items_factura.valor_unitario,   
//         dba.fr_items_factura.valor_total,   
//         dba.fr_items_factura.ind_apropiacion,   
//         dba.fr_items_factura.ind_iva,   
//         dba.fr_items_factura.cod_iva,   
//         dba.fr_items_factura.porc_iva,   
//         dba.fr_items_factura.valor_iva,   
//         dba.fr_items_factura.id_evento  
//    FROM dba.fr_items_factura  
//   WHERE ( dba.fr_items_factura.id_doc_factura = 'FB' ) AND  
//         ( dba.fr_items_factura.id_factura = 3072 )   ;
//  SELECT dba.fr_ganados.id_empresa,   
//         dba.fr_ganados.id_documento,   
//         dba.fr_ganados.id_entrada,   
//         dba.fr_ganados.id_res,   
//         dba.fr_ganados.ind_esp_mayor,   
//         dba.fr_ganados.id_linea,   
//         dba.fr_ganados.id_tipo_corral_r,   
//         dba.fr_ganados.id_corral_r,   
//         dba.fr_ganados.id_tipo_corral_c,   
//         dba.fr_ganados.id_corral_c,   
//         dba.fr_ganados.fec_bscla_indvdual,   
//         dba.fr_ganados.sexo,   
//         dba.fr_ganados.id_bascula,   
//         dba.fr_ganados.id_raza,   
//         dba.fr_ganados.peso,   
//         dba.fr_ganados.descrip_animal,   
//         dba.fr_ganados.estado_animal,   
//         dba.fr_ganados.id_usuario,   
//         dba.fr_ganados.fec_registro,   
//         dba.fr_ganados.id_propietario,   
//         dba.fr_ganados.nombre_propietario,   
//         dba.fr_ganados.id_pesador,   
//         dba.fr_ganados.edad,   
//         dba.fr_ganados.val_unitario_bascula,   
//         dba.fr_ganados.val_unitario_corrales,   
//         dba.fr_ganados.val_unitario_sacrificio,   
//         dba.fr_ganados.ind_pesaje_especial,   
//         dba.fr_ganados.plaza_carne,   
//         dba.fr_ganados.pto_carne,   
//         dba.fr_ganados.plaza_visc,   
//         dba.fr_ganados.pto_visc,   
//         dba.fr_ganados.id_tipo_corral_s,   
//         dba.fr_ganados.id_corral_s,   
//         dba.fr_ganados.id_doc_factura_sac,   
//         dba.fr_ganados.id_factura_sac,   
//         dba.fr_ganados.id_doc_retiros,   
//         dba.fr_ganados.id_retiro,   
//         dba.fr_ganados.ind_peso_manual,   
//         dba.fr_ganados.peso_canal_uno,   
//         dba.fr_ganados.peso_canal_dos,   
//         dba.fr_ganados.peso_total_canal,   
//         dba.fr_ganados.peso_visceras,   
//         dba.fr_ganados.peso_salida_total_canal,   
//         dba.fr_ganados.peso_salida_visceras,   
//         dba.fr_ganados.comprador_piel,   
//         dba.fr_ganados.peso_pierna1,   
//         dba.fr_ganados.peso_pierna2,   
//         dba.fr_ganados.peso_costillar,   
//         dba.fr_ganados.nit_fact_sacrif,   
//         dba.fr_ganados.nombre_fact_sacrif,   
//         dba.fr_ganados.n_intercambios,   
//         dba.fr_ganados.tipo_entrada,   
//         dba.fr_ganados.procedencia,   
//         dba.fr_ganados.fecha_factura_sacrificio,   
//         dba.fr_ganados.ind_propio,   
//         dba.fr_ganados.id_doc_sacr,   
//         dba.fr_ganados.id_sacr,   
//         dba.fr_ganados.val_unitario_flete  
//    FROM dba.fr_ganados  
//   WHERE dba.fr_ganados.id_entrada = 10347   ;
