CREATE TABLE dba.fr_lineas
(
	id_empresa		char(2) NOT NULL,
	id_linea		char(2) NOT NULL,
	descripcion		varchar(60) NOT NULL,
	ind_especie_mayor		char(1) NOT NULL,
	id_usuario		char(4),
	fec_registro		datetime,
	PRIMARY KEY (id_empresa, id_linea),
);
CREATE TABLE dba.fr_conceptos_facturacion
(
	id_empresa		char(2) NOT NULL,
	id_evento		char(2) NOT NULL,
	ind_esp_mayor		char(1) NOT NULL,
	id_linea		char(2) NOT NULL,
	id_concepto		char(4) NOT NULL,
	descripcion		varchar(60) NOT NULL,
	id_unidad		char(2) NOT NULL,
	val_unitario		numeric(12,2) NOT NULL,
	ind_apropiacion		char(1) NOT NULL,
	nit_destinatario		char(15),
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	ind_iva		char(1),
	cod_iva		char(4),
	porc_iva		numeric(4,2),
	val_unitario_especial		numeric(12,2),
	cuenta_debito		char(20),
	cuenta_credito		char(20),
	destino		char(12),
	subdestino		char(12),
	PRIMARY KEY (id_empresa, id_evento, ind_esp_mayor, id_linea, id_concepto),
);
ALTER TABLE dba.fr_conceptos_facturacion
	ADD FOREIGN KEY (id_empresa,id_linea) REFERENCES dba.fr_lineas (id_empresa,id_linea);


CREATE TABLE dba.fr_enc_entrada
(
	id_empresa		char(2) NOT NULL,
	id_documento		char(2) NOT NULL,
	id_entrada		numeric(6,0) NOT NULL,
	fecha_ingreso		datetime NOT NULL,
	tipo_entrada		char(2) NOT NULL,
	ind_esp_mayor		char(1) NOT NULL,
	id_linea		char(2) NOT NULL,
	ind_propio		char(1) NOT NULL,
	id_propietario		char(15) NOT NULL,
	nombre_propietario		varchar(60) NOT NULL,
	procedencia		char(3) NOT NULL,
	vehiculo		char(15) NOT NULL,
	id_conductor		char(15) NOT NULL,
	nombre_conductor		varchar(60) NOT NULL,
	id_tipo_corral_r		char(2) NOT NULL,
	id_corral_r		char(3) NOT NULL,
	estado_entrada		char(1) NOT NULL,
	observaciones		varchar(255),
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	peso_global_lote		numeric(16,2),
	ind_bascula		char(1) NOT NULL,
	fec_bascula		datetime,
	usuario_bascula		char(4),
	numero_guia		char(15) NOT NULL,
	nmro_reg_sanitario		char(15) NOT NULL,
	usr_ingreso		char(4),
	nmro_bono_venta		char(15),
	cant_animales		numeric(3,0),
	id_tipo_corral_c		char(2),
	id_corral_c		char(3),
	usr_corral_c		char(4),
	fec_corral_c		datetime,
	secuencia_pesaje		numeric(5,0),
	secuencia_subasta		numeric(5,0),
	usr_secuencia_subasta		char(4),
	fec_sec_subasta		datetime,
	prec_base_kilo		numeric(16,2),
	prec_final_base_kilo		numeric(16,2),
	id_doc_fact_vtas_subasta		char(2),
	id_fact_vtas_subasta		numeric(6,0),
	consec_subasta		numeric(6,0),
	PRIMARY KEY (id_empresa, id_documento, id_entrada),
);
CREATE TABLE dba.fr_items_entrada
(
	id_empresa		char(2) NOT NULL,
	id_documento		char(2) NOT NULL,
	id_entrada		numeric(6,0) NOT NULL,
	id_tipo_animal		char(2) NOT NULL,
	cantidad		numeric(2,0) NOT NULL,
	ind_esp_mayor		char(1) NOT NULL,
	PRIMARY KEY (id_empresa, id_documento, id_entrada, id_tipo_animal),
);
ALTER TABLE dba.fr_items_entrada
	ADD FOREIGN KEY (id_empresa,id_documento,id_entrada) REFERENCES dba.fr_enc_entrada (id_empresa,id_documento,id_entrada);

CREATE TABLE dba.fr_ganados
(
	id_empresa		char(2) NOT NULL,
	id_documento		char(2) NOT NULL,
	id_entrada		numeric(6,0) NOT NULL,
	id_res		char(8) NOT NULL,
	ind_esp_mayor		char(1) NOT NULL,
	id_linea		char(2) NOT NULL,
	id_tipo_corral_r		char(2) NOT NULL,
	id_corral_r		char(3) NOT NULL,
	id_tipo_corral_c		char(2) NOT NULL,
	id_corral_c		char(3) NOT NULL,
	fec_bscla_indvdual		datetime NOT NULL,
	sexo		char(1) NOT NULL,
	id_bascula		char(2) NOT NULL,
	id_raza		char(2),
	peso		numeric(16,2) NOT NULL,
	descrip_animal		varchar(100),
	estado_animal		char(1) NOT NULL,
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	id_propietario		char(15) NOT NULL,
	nombre_propietario		varchar(60) NOT NULL,
	id_pesador		char(4) NOT NULL,
	edad		numeric(3,0),
	val_unitario_bascula		numeric(16,2),
	val_unitario_corrales		numeric(16,2),
	val_unitario_sacrificio		numeric(16,2),
	ind_pesaje_especial		char(1),
	plaza_carne		char(2),
	pto_carne		char(4),
	plaza_visc		char(2),
	pto_visc		char(4),
	id_tipo_corral_s		char(2),
	id_corral_s		char(3),
	id_doc_factura_sac		char(2),
	id_factura_sac		numeric(6,0),
	id_doc_retiros		char(2),
	id_retiro		numeric(6,0),
	ind_peso_manual		char(1),
	peso_canal_uno		numeric(16,2),
	peso_canal_dos		numeric(16,2),
	peso_total_canal		numeric(16,2),
	peso_visceras		numeric(16,2),
	peso_salida_total_canal		numeric(16,2),
	peso_salida_visceras		numeric(16,2),
	comprador_piel		varchar(60),
	peso_pierna1		numeric(16,2),
	peso_pierna2		numeric(16,2),
	peso_costillar		numeric(16,2),
	nit_fact_sacrif		char(15),
	nombre_fact_sacrif		varchar(60),
	n_intercambios		numeric(6,0),
	PRIMARY KEY (id_empresa, id_documento, id_entrada, id_res),
);

CREATE TABLE dba.fr_encab_factura
(
	id_empresa		char(2) NOT NULL,
	id_doc_factura		char(2) NOT NULL,
	id_factura		numeric(6,0) NOT NULL,
	id_doc		char(2) NOT NULL,
	id_entrada		numeric(6,0) NOT NULL,
	id_fact_prmprso		numeric(6,0) NOT NULL,
	cod_alterno		varchar(15),
	fec_factura		datetime NOT NULL,
	ind_lin_mayor		char(1) NOT NULL,
	id_especie		char(2) NOT NULL,
	id_propietario		char(15) NOT NULL,
	nombre_propietario		varchar(60) NOT NULL,
	total_factura		numeric(16,2) NOT NULL,
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	ind_pagado		char(1) NOT NULL,
	id_comprador		char(15),
	nombre_comprador		varchar(60),
	nit_factura		char(15) NOT NULL,
	nombre_factura		varchar(60) NOT NULL,
	tipo_entrada		char(2),
	cant_animales		numeric(3,0),
	total_kilos		numeric(10,2),
	fecha_ingreso		datetime,
	total_fact_sin_iva		numeric(16,2) NOT NULL,
	total_iva_fact		numeric(16,2) NOT NULL,
	total_factura_letras		varchar(200),
	id_evento_fac		char(2),
	n_paleta		numeric(5,0),
	n_subasta		numeric(6,0),
	prec_base_kilo		numeric(16,2),
	prec_final_base_kilo		numeric(16,2),
	id_comprobante		char(2),
	cod_comprobante		numeric(6,0),
	estado_contable		char(1),
	PRIMARY KEY (id_empresa, id_doc_factura, id_factura),
);

CREATE TABLE dba.fr_items_factura
(
	id_empresa		char(2) NOT NULL,
	id_doc_factura		char(2) NOT NULL,
	id_factura		numeric(6,0) NOT NULL,
	id_concepto		char(4) NOT NULL,
	ind_lin_mayor		char(1) NOT NULL,
	id_especie		char(2) NOT NULL,
	unidad_concepto		char(2) NOT NULL,
	cantidad_concepto		numeric(16,2) NOT NULL,
	valor_unitario		numeric(16,2) NOT NULL,
	valor_total		numeric(16,2) NOT NULL,
	ind_apropiacion		char(1) NOT NULL,
	ind_iva		char(1) NOT NULL,
	cod_iva		char(4),
	porc_iva		numeric(4,2),
	valor_iva		numeric(16,2),
	id_evento		char(2) NOT NULL,
	PRIMARY KEY (id_empresa, id_doc_factura, id_factura, id_concepto),
);

ALTER TABLE dba.fr_items_factura
	ADD FOREIGN KEY (id_empresa,id_doc_factura,id_factura) REFERENCES dba.fr_encab_factura (id_empresa,id_doc_factura,id_factura);

ALTER TABLE dba.fr_items_factura
	ADD FOREIGN KEY (id_empresa,id_evento,ind_lin_mayor,id_especie,id_concepto) REFERENCES dba.fr_conceptos_facturacion (id_empresa,id_evento,ind_esp_mayor,id_linea,id_concepto);

CREATE TABLE dba.fr_plazas
(
	id_empresa		char(2) NOT NULL,
	id_plaza		char(2) NOT NULL,
	descripcion		varchar(60) NOT NULL,
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	id_tipo_corral_s_mayor		char(2),
	id_corral_s_mayor		char(3),
	id_tipo_corral_s_menor		char(2),
	id_corral_s_menor		char(3),
	PRIMARY KEY (id_empresa, id_plaza),
);

CREATE TABLE dba.fr_puestos_x_plaza
(
	id_empresa		char(2) NOT NULL,
	id_plaza		char(2) NOT NULL,
	id_puesto		char(4) NOT NULL,
	nit_propietario		char(15),
	nombre_propietario		varchar(60),
	id_usuario		char(4),
	fec_registro		datetime,
	PRIMARY KEY (id_empresa, id_plaza, id_puesto),
);

ALTER TABLE dba.fr_puestos_x_plaza
	ADD FOREIGN KEY (id_empresa,id_plaza) REFERENCES dba.fr_plazas (id_empresa,id_plaza);

CREATE TABLE dba.fr_recaudo
(
	id_empresa		char(2) NOT NULL,
	id_recaudo		char(2) NOT NULL,
	num_recaudo		numeric(6,0) NOT NULL,
	id_evento_fac		char(2) NOT NULL,
	id_factura		char(2) NOT NULL,
	num_factura		numeric(6,0) NOT NULL,
	impreso_factura		numeric(6,0) NOT NULL,
	total_factura		numeric(16,2) NOT NULL,
	total_fac_sin_iva		numeric(16,2) NOT NULL,
	total_iva_fac		numeric(16,2) NOT NULL,
	nit_factura		char(15) NOT NULL,
	nombre_factura		varchar(60) NOT NULL,
	id_medio_pago		char(2) NOT NULL,
	dinero_entregado		numeric(16,2) NOT NULL,
	id_banco		char(15),
	num_cuenta		varchar(20),
	num_cheque		varchar(20),
	telefonos		varchar(30),
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	fec_recaudo		datetime NOT NULL,
	fec_cheque		datetime,
	usr_anula		char(4),
	fec_anula		datetime,
	estado		char(1),
	num_bono		numeric(6,0),
	efectivo_mixto		numeric(16,2),
	cheque_mixto		numeric(16,2),
	bono_mixto		numeric(16,2),
	credito_mixto		numeric(16,2),
	dias_credito		numeric(3,0),
	PRIMARY KEY (id_empresa, id_recaudo, num_recaudo),
);


