CREATE TABLE dba.fr_enc_rechazos
(
	id_empresa		char(2) NOT NULL,
	id_documento		char(2) NOT NULL,
	id_rechazo		numeric(6,0) NOT NULL,
	fecha_rechazo		datetime NOT NULL,
	tipo_entrada		char(2) NOT NULL,
	ind_linea_mayor		char(1) NOT NULL,
	id_especie		char(2) NOT NULL,
	ind_propio		char(1) NOT NULL,
	id_propietario		char(15) NOT NULL,
	nombre_propietario		varchar(60) NOT NULL,
	procedencia		char(3) NOT NULL,
	vehiculo		char(15) NOT NULL,
	id_conductor		char(15) NOT NULL,
	nombre_conductor		varchar(60) NOT NULL,
	estado_rechazo		char(1) NOT NULL,
	observaciones		varchar(255),
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	cant_animales		numeric(3,0) NOT NULL,
	numero_guia		char(15),
	numero_reg_sanitario		char(15),
	numero_bono_venta		char(15),
	causal		char(1) NOT NULL,
	PRIMARY KEY (id_empresa, id_documento, id_rechazo),
);

CREATE TABLE dba.fr_items_rechazos
(
	id_empresa		char(2) NOT NULL,
	id_documento		char(2) NOT NULL,
	id_rechazo		numeric(6,0) NOT NULL,
	id_tipo_animal		char(2) NOT NULL,
	cantidad		numeric(2,0) NOT NULL,
	ind_lin_mayor		char(1) NOT NULL,
	PRIMARY KEY (id_empresa, id_documento, id_rechazo, id_tipo_animal),
);
ALTER TABLE dba.fr_items_rechazos
	ADD FOREIGN KEY (id_empresa,id_documento,id_rechazo) REFERENCES dba.fr_enc_rechazos (id_empresa,id_documento,id_rechazo);
CREATE TABLE dba.fr_encab_retiros
(
	id_empresa		char(2) NOT NULL,
	id_doc_retiros		char(2) NOT NULL,
	id_retiro		numeric(6,0) NOT NULL,
	fec_retiro		datetime NOT NULL,
	ind_lin_mayor		char(1) NOT NULL,
	id_especie		char(2) NOT NULL,
	id_nit_retiro		char(15) NOT NULL,
	nombre_retiro		varchar(60) NOT NULL,
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	cant_animales		numeric(3,0) NOT NULL,
	PRIMARY KEY (id_empresa, id_doc_retiros, id_retiro),
);

CREATE TABLE dba.fr_usrio_peso_manual
(
	id_empresa		char(2) NOT NULL,
	id_usuario		char(4) NOT NULL,
	PRIMARY KEY (id_empresa, id_usuario),
);

CREATE TABLE dba.fr_canales
(
	id_empresa		char(2) NOT NULL,
	id_documento		char(2) NOT NULL,
	id_entrada		numeric(6,0) NOT NULL,
	id_res		char(8) NOT NULL,
	peso_canal_uno		numeric(16,2) NOT NULL,
	peso_canal_dos		numeric(16,2) NOT NULL,
	peso_total_canal		numeric(16,2) NOT NULL,
	peso_visceras		numeric(16,2) NOT NULL,
	estado		char(1) NOT NULL,
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	peso_total_salida_canal		numeric(16,2),
	peso_salida_visceras		numeric(16,2),
	peso_pierna_1		numeric(16,2),
	peso_pierna_2		numeric(16,2),
	peso_costillar		numeric(16,2),
	fec_ingreso		datetime,
	PRIMARY KEY (id_empresa, id_documento, id_entrada, id_res),
);

CREATE TABLE dba.fr_encab_subasta
(
	id_empresa		char(2) NOT NULL,
	id_doc_subasta		char(2) NOT NULL,
	consec_subasta		numeric(6,0) NOT NULL,
	fecha_subasta		datetime NOT NULL,
	num_animales		numeric(16,0) NOT NULL,
	vlr_total_venta		numeric(16,2) NOT NULL,
	vlr_total_comision		numeric(16,2) NOT NULL,
	estado		char(1) NOT NULL,
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	PRIMARY KEY (id_empresa, id_doc_subasta, consec_subasta),
);

CREATE TABLE dba.fr_ganados_hist
(
	id_empresa		char(2) NOT NULL,
	id_documento		char(2) NOT NULL,
	id_entrada		numeric(6,0) NOT NULL,
	id_res		char(8) NOT NULL,
	ind_esp_mayor		char(1) NOT NULL,
	id_linea		char(2) NOT NULL,
	id_tipo_corral_r		char(2) NOT NULL,
	id_corral_r		char(3) NOT NULL,
	id_tipo_corral_c		char(2) NOT NULL,
	id_corral_c		char(3) NOT NULL,
	fec_bscla_indvdual		datetime NOT NULL,
	sexo		char(1) NOT NULL,
	id_bascula		char(2) NOT NULL,
	id_raza		char(2),
	peso		numeric(16,2) NOT NULL,
	descrip_animal		varchar(100),
	estado_animal		char(1) NOT NULL,
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	id_propietario		char(15) NOT NULL,
	nombre_propietario		varchar(60) NOT NULL,
	id_pesador		char(4) NOT NULL,
	edad		numeric(3,0),
	val_unitario_bascula		numeric(16,2),
	val_unitario_corrales		numeric(16,2),
	val_unitario_sacrificio		numeric(16,2),
	ind_pesaje_especial		char(1),
	plaza_carne		char(2),
	pto_carne		char(4),
	plaza_visc		char(2),
	pto_visc		char(4),
	id_tipo_corral_s		char(2),
	id_corral_s		char(3),
	id_doc_factura_sac		char(2),
	id_factura_sac		numeric(6,0),
	id_doc_retiros		char(2),
	id_retiro		numeric(6,0),
	ind_peso_manual		char(1),
	peso_canal_uno		numeric(16,2),
	peso_canal_dos		numeric(16,2),
	peso_total_canal		numeric(16,2),
	peso_visceras		numeric(16,2),
	peso_salida_total_canal		numeric(16,2),
	peso_salida_visceras		numeric(16,2),
	comprador_piel		varchar(60),
	peso_pierna1		numeric(16,2),
	peso_pierna2		numeric(16,2),
	peso_costillar		numeric(16,2),
	nit_fact_sacrif		char(15),
	nombre_fact_sacrif		varchar(60),
	PRIMARY KEY (id_empresa, id_documento, id_entrada, id_res),
);
CREATE TABLE dba.fr_canales_hist
(
	id_empresa		char(2) NOT NULL,
	id_documento		char(2) NOT NULL,
	id_entrada		numeric(6,0) NOT NULL,
	id_res		char(8) NOT NULL,
	peso_canal_uno		numeric(16,2) NOT NULL,
	peso_canal_dos		numeric(16,2) NOT NULL,
	peso_total_canal		numeric(16,2) NOT NULL,
	peso_visceras		numeric(16,2) NOT NULL,
	estado		char(1) NOT NULL,
	id_usuario		char(4) NOT NULL,
	fec_registro		datetime NOT NULL,
	peso_total_salida_canal		numeric(16,2),
	peso_salida_visceras		numeric(16,2),
	peso_pierna_1		numeric(16,2),
	peso_pierna_2		numeric(16,2),
	peso_costillar		numeric(16,2),
	fec_ingreso		datetime,
	PRIMARY KEY (id_empresa, id_documento, id_entrada, id_res),
);
CREATE TABLE dba.fr_log_intercambios
(
	id_empresa		char(2) NOT NULL,
	id_entrada_out		numeric(6,0) NOT NULL,
	animal_out		char(8) NOT NULL,
	id_entrada_in		numeric(6,0) NOT NULL,
	animal_in		char(8) NOT NULL,
	fecha_intercambio		datetime NOT NULL,
	id_usuario		char(4) NOT NULL,
	nombre_usuario		varchar(60) NOT NULL,
	PRIMARY KEY (id_empresa, id_entrada_out, animal_out),
);

CREATE TABLE dba.fr_prog_sacrif_mayor
(
	id_empresa		char(2) NOT NULL,
	consec		numeric(8,0) NOT NULL,
	uno_plaza		char(2),
	dos_pto		char(4),
	tres_animal		char(8),
	cuatro_peso		numeric(16,2),
	cinco_sexo		char(1),
	seis_plaza		char(2),
	siete_pto		char(4),
	ocho_animal		char(8),
	nueve_peso		numeric(16,2),
	diez_sexo		char(1),
	once_plaza		char(2),
	doce_pto		char(4),
	trece_animal		char(8),
	catorce_peso		numeric(16,2),
	quince_sexo		char(1),
	diezyseis_plaza		char(2),
	diezysiete_pto		char(4),
	diezyocho_animal		char(8),
	diezynueve_peso		numeric(16,2),
	veinte_sexo		char(1),
	veintiuno_plaza		char(2),
	veintidos_pto		char(4),
	veintitres_animal		char(8),
	venticuatro_peso		numeric(16,2),
	veinticinco_sexo		char(1),
	veintiseis_plaza		char(2),
	veintisiete_pto		char(4),
	veintiocho_animal		char(8),
	veintinueve_peso		numeric(16,2),
	treinta_sexo		char(1),
	treintayuno_plaza		char(2),
	treintaydos_pto		char(4),
	treintaytres_animal		char(8),
	treintaycuatro_peso		numeric(16,2),
	treintraycinco_sexo		char(1),
	treintayseis_plaza		char(2),
	treintaysiete_pto		char(4),
	treintayocho_animal		char(8),
	treintaynueve_peso		numeric(16,2),
	cuarenta_sexo		char(1),
	cuarentayuno_plaza		char(2),
	cuarentaydos_pto		char(4),
	cuarentaytres_animal		char(8),
	cuarentaycuatro_peso		numeric(16,2),
	cuarentaycinco_sexo		char(1),
	cuarentayseis_plaza		char(2),
	cuarentaysiete_pto		char(4),
	cuarentayocho_animal		char(8),
	cuarentaynueve_peso		numeric(16,2),
	cincuenta_sexo		char(1),
	dos_pto_visc		char(4),
	siete_pto_visc		char(4),
	doce_pto_visc		char(4),
	diezysiete_pto_visc		char(4),
	veintidos_pto_visc		char(4),
	veintisiete_pto_visc		char(4),
	treintaydos_pto_visc		char(4),
	treintaysiete_pto_visc		char(4),
	cuarentaydos_pto_visc		char(4),
	cuarentaysiete_pto_visc		char(4),
	PRIMARY KEY (id_empresa, consec),
);

