//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18010
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 
namespace WebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Actualiza_Peso_Sacrificio_VijagualPortBinding", Namespace="http://Vijagual.Sacrificio.com/")]
    public partial class Actualiza_Peso_Sacrificio_Vijagual : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ActualizaPesoSacrificioVijagualOperationCompleted;
        
        /// <remarks/>
        public Actualiza_Peso_Sacrificio_Vijagual() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["EndpointURL"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://192.168.6.63:8080/FrigorificoVijagualWSAppPeso/Actualiza_Peso_Sacrificio_V" +
                    "ijagual";
            }
        }
        
        /// <remarks/>
        public event ActualizaPesoSacrificioVijagualCompletedEventHandler ActualizaPesoSacrificioVijagualCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Vijagual.Sacrificio.com/", ResponseNamespace="http://Vijagual.Sacrificio.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActualizaPesoSacrificioVijagual([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int codigoLote, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string codigoAnimal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] double peso, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] double peso2) {
            object[] results = this.Invoke("ActualizaPesoSacrificioVijagual", new object[] {
                        codigoLote,
                        codigoAnimal,
                        peso,
                        peso2});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginActualizaPesoSacrificioVijagual(int codigoLote, string codigoAnimal, double peso, double peso2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ActualizaPesoSacrificioVijagual", new object[] {
                        codigoLote,
                        codigoAnimal,
                        peso,
                        peso2}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndActualizaPesoSacrificioVijagual(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizaPesoSacrificioVijagualAsync(int codigoLote, string codigoAnimal, double peso, double peso2) {
            this.ActualizaPesoSacrificioVijagualAsync(codigoLote, codigoAnimal, peso, peso2, null);
        }
        
        /// <remarks/>
        public void ActualizaPesoSacrificioVijagualAsync(int codigoLote, string codigoAnimal, double peso, double peso2, object userState) {
            if ((this.ActualizaPesoSacrificioVijagualOperationCompleted == null)) {
                this.ActualizaPesoSacrificioVijagualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizaPesoSacrificioVijagualOperationCompleted);
            }
            this.InvokeAsync("ActualizaPesoSacrificioVijagual", new object[] {
                        codigoLote,
                        codigoAnimal,
                        peso,
                        peso2}, this.ActualizaPesoSacrificioVijagualOperationCompleted, userState);
        }
        
        private void OnActualizaPesoSacrificioVijagualOperationCompleted(object arg) {
            if ((this.ActualizaPesoSacrificioVijagualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizaPesoSacrificioVijagualCompleted(this, new ActualizaPesoSacrificioVijagualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ActualizaPesoSacrificioVijagualCompletedEventHandler(object sender, ActualizaPesoSacrificioVijagualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizaPesoSacrificioVijagualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizaPesoSacrificioVijagualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
